name: Tests
on: [push]

jobs:
  runtime-test:
    name: Verify consistency with original manuform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.10.1.693
          lein: 2.9.1

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install npm dependencies
        run: npm ci

      - name: Compile code
        run: make all

      - name: Build site
        run: npm run build

      - name: Test code
        run: npm test
